trigger: none

variables:
  projectName: 'FunctionApp1'
  tfVarsFilePath: '$(System.DefaultWorkingDirectory)/Projects/app1.tfvars'

stages:
- template: ../Common/templates/azfunc-tftemplate-pipeline.yml
  parameters:     
    projectName: $(projectName)
    tfVarsFilePath: $(tfVarsFilePath)


    
    
   
